plugin:
  name: "help"
  description: "offers help"
  methods:
    - name: "general_help"
      keywords:
        list:
          - "kannst du mir( bitte)? helfen"
          - "ich brauche hilfe"
          - "ich wei√ü nicht was ich (machen|tun){1} soll"
      answers:
        list:
          - "$help"
        params:
          - name: help
            description: "the help"

